name: CI

on:
  push:
    branches: [ "actions" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: master
          elixir-version: main
      - name: PLT cache
        uses: actions/cache@v4
        id: plt_cache
        with:
          key: plt
          path: priv/plts
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: mix deps.get
      - name: Check for compilation errors
        run: mix compile --warnings-as-errors
      - name: Check code formatting
        run: mix format --check-formatted
      - name: Analyze code with Credo
        run: mix credo --strict
      - name: Analyze code with Dialyzer
        run: mix dialyzer --format dialyzer

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir:
          - 1.17.x
        otp:
          - 27.x
          - 26.x
          - 25.x
        include:
          - elixir: main
            otp: master
          - elixir: 1.16.x
            otp: 26.x
          - elixir: 1.15.x
            otp: 26.x
          - elixir: 1.14.x
            otp: 25.x
          - elixir: 1.13.x
            otp: 24.x
          - elixir: 1.12.x
            otp: 24.x
          - elixir: 1.11.x
            otp: 24.x

    steps:
      - name: Set up Erlang and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get dependencies
        run: mix deps.get
      - name: Run tests
        run: mix test
